USE db_curso_web;

/**
* USANDO AGRUPAMENTO DE SELEÇÃO - AGRUPA UM OU MAIS COLUNAS CUJOS OS VALORES SÃO IGUAIS, INFORMANDO APENAS UM LINHA
* MOSTRANDO COMO SE FOSSE SUBCONJUNTO DAQUELA CATEGORIA QUE HOUVE MAIS DE UM REGISTRO
* PERMITE REALIZAR FUNÇÕES DE AGREGAÇÃO EM CADA SUBCONJUNTO AGRUPADO DE REGISTRO
* GROUP BY - RESPONDER PERGUNTAS QUAIS, QUAL O TOTAL DE ALUNOS POR CURSO? QUAL O TOTAL DE CATEGORIA POR CURSO?
* GROUP BY - DEVE VIR DEPOIS DA TABELA QUANDO WHERE NÃO ESTA DECLARADO, CASO ESTEJA DEVE VIR DEPOIS DO WHERE
* GROUP BY - DEVE FICAR ANTES DO ORDER BY E POR FIM LIMIT FICARÁ SEMPRE NO FINAL DE CADA INSTRUÇÃO
*/

# QUANTOS REGISTROS DE ALUNOS EXISTES AGRUPADOS PELOS SEUS INTERESSES
SELECT * FROM tb_alunos WHERE interesse = 'Jogos';
SELECT * FROM tb_alunos WHERE interesse = 'Música';
SELECT * FROM tb_alunos GROUP BY interesse;
SELECT *, COUNT(*) FROM tb_alunos GROUP BY interesse;
SELECT interesse, COUNT(*) FROM tb_alunos GROUP BY interesse;

# (AS) USADO PARA APELIDAR COLUNAS
SELECT interesse, COUNT(*) AS total_interesse FROM tb_alunos GROUP BY interesse;

# QUERY DE REGISTRO AGRUPADOS PELOS ESTADOS
SELECT estado, COUNT(*) AS total_estado FROM tb_alunos GROUP BY estado;