USE db_curso_web;
# ORDER BY - SE HOVER WHERE DEVE VIR APÓS 
# ORDER BY - SE NÃO HOVER WHERE DEVE VIR DEPOIS DA TABELA
# ASC - ACENDENTE
# DESC - DESCENDENTE

# O USO DE ORDER BY PRECISA DE UMA COLUNA COMO BASE PARA SUA ORDENAÇÃO 
SELECT * FROM tb_alunos WHERE idade BETWEEN 16 AND 59 ORDER BY nome DESC;
SELECT * FROM tb_alunos WHERE idade BETWEEN 16 AND 59 ORDER BY nome ASC, idade DESC, estado ASC;
