USE db_curso_web;

# LIMITE É ÚTIL QUANDO EM UMA TABELA EXISTE CENTENAS DE REGISTRO E SEU RETORNO É EXCESSÍVO
# EXEMPLO É PÁGINAS EXISTE CENTENAS DE PÁGINAS PORÉM, É EXIBIDO SOMENTE UM LIMITE PRE-ESTABELECIDO
# DEVE SER COLOCADO SEMPRE NO FINAL DA QUERY
# OFFSET DEVE SER DECLARADO SOMENTE SE LIMIT FOR DECLARADO NA INTRUÇÃO E FUNCIONA COMO DESLOCAMENTO

# QUERY SIMPLES COM LIMITE DE 25 REGISTROS
SELECT * FROM tb_alunos LIMIT 25;
SELECT * FROM tb_alunos ORDER BY nome ASC LIMIT 10;

# A PARTIR DO REGISTRO 0 TRAZER SOMENTE 4 REGISTRO
SELECT * FROM tb_alunos LIMIT 4 OFFSET 0;

# A PARTIR DO 4 REGISTRO TRAZER SOMENTE 4 REGISTRO
SELECT * FROM tb_alunos LIMIT 4 OFFSET 4;
SELECT * FROM tb_alunos LIMIT 4 OFFSET 8;

# OMITINDO OFFSET - DEIXANDO APENAS A INTRUÇÃO LIMIT
# PRIMERIO PARÂMETRO É OFFSET E O SEGUINTE É O LIMITE
SELECT * FROM tb_alunos LIMIT 0,4;