USE db_curso_web;

/**
* RELACIONAMENTO ENTRE TABELAS - EXISTE TRÊS TIPOS DE RELACIONAMENTOS DE TABELAS
* UM PARA UM
* UM PARA MUITOS
* MUITOS PARA MUITOS
*
* CHAVES PRIMÁRIAS - PRIMARY KEY() - IDENTIFICADOR ÚNICO PARA CADA REGISTROS
* CHAVES ESTRANGEIRAS - FOREING KEY() - REFERÊNCIA DE CHAVE PRIMÁRIA DE OUTRA TABELA
*/